repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-yaml
  - id: check-added-large-files
  - id: detect-private-key
- repo: https://github.com/psf/black
  rev: 21.10b0
  hooks:
  - id: black
  - id: black-jupyter
- repo: https://github.com/PyCQA/isort
  rev: 5.10.0
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    require_serial: true
